# Pulling Ubuntu image
FROM ubuntu:20.04

# install cron, python3 and pip
RUN apt-get update && apt-get install cron python3 python3-pip -y 

# copy MQ client installable
COPY 9.1.0.15-IBM-MQC-UbuntuLinuxX64.tar.gz /tmp

WORKDIR /var/scripts

COPY startup/* startup/
RUN chmod +x startup/installMQClient.sh

# run script to install MQ client
RUN startup/installMQClient.sh

# install python packages
RUN pip install -r startup/python_pkgs.txt

# start the cron service
#CMD python3 /var/python/scripts/mqutil.py ; cron -f
CMD python3 startup/init.py ; cron -f
