# Pulling Ubuntu image
FROM ubuntu:20.04

# install cron, python3 and pip
RUN apt-get update && apt-get install cron python3 python3-pip -y 

# copy MQ client installable
COPY 9.1.0.15-IBM-MQC-UbuntuLinuxX64.tar.gz /tmp

WORKDIR /var/scripts

COPY *.sh *.txt *.py *.json /var/python/scripts/
RUN chmod +x /var/python/scripts/installMQClient.sh

# run script to install MQ client
RUN /var/python/scripts/installMQClient.sh

# install python packages
RUN pip install -r /var/python/scripts/python_pkgs.txt

# start the cron service
#CMD python3 /var/python/scripts/mqutil.py ; cron -f
CMD service cron start ; python3 /var/python/scripts/mqutil.py
